### ISSUE TITLE
[Feature] Safeguard against bad actors (custom build scripts)

### ISSUE THREAD

**Issue by mattpolzin** [stefan-hoeck/idris2-pack#10]
We've got a lovely Idris community but if/when `pack` starts running arbitrary extra code as part of the building or installation of dependencies I would love to see (as an additive feature, not a pre-requisite) some safe guards against unexpected side effects. 

Deno (NodeJS "successor") takes a permissions stance where the user running code must ok various kinds of things like making network requests or reading/writing to disk. That's an interesting angle to think about, but I think something as simple as a prompt for confirmation right before a dependency with custom build scripts is built would be great. 

It's not all about bad actors, either. It's nice not to surprise the person running a build even if you're not doing anything malicious.

**Comment by stefan-hoeck** [comment]
This is a great idea. Ideally, such a security measure would come with a command line option to turn prompting of (for instance when checking data collections automatically).

**Comment by stefan-hoeck** [comment]
This was implemented in #31  together with some command-line options and a setting in the `pack.toml` for explicitly turning it on or off (it is turned on as a default). It's just a prompt for confirmation in case of custom build- or install hooks, however.

**Comment by stefan-hoeck** [comment]
A simple safeguard has been implemented quite a while ago, together with command-line options and a `pack.toml` setting for turning this safeguard off. In addition and as suggested in #177, a "whitelist" setting was added to `pack.toml` files in #186, which allows users to turn off the safeguard only for certain trusted packages.

Since I try to keep up with feature request and clean up the issue tracker a bit, I'll close this as implemented. Feel free to reopen (or open a new issue), if you think the current safety measures are not enough.
