### ISSUE TITLE
Proper git cache

### ISSUE THREAD

**Issue by locriacyber** [stefan-hoeck/idris2-pack#142]
Currently, Pack only stores one git repo at `~/.pack/tmp` (I think it's here) when installing packages. It also deletes the directory when killed politely.

Several problems:
- Sometimes I need to debug build issues of a package downloaded with Pack (because it can't build). When pack exited abnormally or killed, it should not delete the git repo, but leave it on the disk.
- The local path is fixed. I would be better if the git path is stored in `~/.cache/pack/git/repo-name`, so multiple git repos can be cached.
- As for being cached, I often have 1 git repo for a package locally for development, and Pack downloads it from Internet again. It would be nice to allow having multiple git remotes. For example, Pack would check if a commit is available in the local version first, and use that to build the package. This should be as simple as `git clone local/git/repo -b <HASH>`.

**Comment by stefan-hoeck** [comment]
> Currently, Pack only stores one git repo at `~/.pack/tmp` (I think it's here) when installing packages. It also deletes the directory when killed politely.

No. The latest versions of pack use different locations for downloaded libraries. Please update your pack implementation.

> Several problems:
> 
>     * Sometimes I need to debug build issues of a package downloaded with Pack (because it can't build). When pack exited abnormally or killed, it should not delete the git repo, but leave it on the disk.

I'd rather have pack clean up after itself instead of leaving broken builds lying around here and there. If you need to fix a package that no longer builds, some manual work is required anyway, so it's not such a big thing to manually clone the GitHub repo and see what's wrong.

>     * The local path is fixed. I would be better if the git path is stored in `~/.cache/pack/git/repo-name`, so multiple git repos can be cached.

Pack is not about caching git repos. The big advantage of cloning a repo from GitHub before building it is that we get a fresh and clean build. This is not guaranteed with cached repos.

>     * As for being cached, I often have 1 git repo for a package locally for development, and Pack downloads it from Internet again. It would be nice to allow having multiple git remotes. For example, Pack would check if a commit is available in the local version first, and use that to build the package. This should be as simple as `git clone local/git/repo -b <HASH>`.

I'm reluctant to complicate the package situation even further by letting pack check for local clones of GitHub repos. See also my comment above about the advantages of clean builds. Also, you can already use a local copy of a GitHub repo by listing it as a local package in one of the `pack.toml` files in scope. You will be responsible of fetching updates from GitHub yourself, however.

Have you seen the two example projects in this repo about developing packages with pack?

**Comment by stefan-hoeck** [comment]
I have been thinking this over a bit, and I have a couple of questions. Assuming we would cache the GitHub repos downloaded by pack.

* With the command you gave above (`git clone /path/to/cached/repo/ -b <HASH> /path/to/tmp/repo`), we'd get access to the desired commit hash and a clean build environment at `/path/to/tmp/repo`, correct?
* What if `<HASH>` wasn't there yet, because we'd first need to pull the latest commits? Is there a clean command to check for that? Or should we just pull whenever we build a package just to make sure?
* I'm still not sure whether it will be possible to support local GitHub clones the user is working on (other than using the existing methods provided by local packages defined in `pack.toml` files), so perhaps we should first just focus on cached git repos?

What do you think?

**Comment by stefan-hoeck** [comment]
> > With the command you gave above (git clone /path/to/cached/repo/ -b  /path/to/tmp/repo), we'd get access to the desired commit hash and a clean build environment at /path/to/tmp/repo, correct?
> 
> Yes. Use `git clone --depth 1 --bare` to save space.
> 
> > What if  wasn't there yet, because we'd first need to pull the latest commits? Is there a clean command to check for that? Or should we just pull whenever we build a package just to make sure?
> 
> Use `git fetch origin <HASH> --depth 1` in the cached repo, then try again.

My question was, is there a git command for checking whether a certain commit is there or not?

> > I'm still not sure whether it will be possible to support local GitHub clones the user is working on (other than using the existing methods provided by local packages defined in pack.toml files), so perhaps we should first just focus on cached git repos?
> 
> I think yes. I'll check out your examples of working on projects locally.

That would be great.
 
> I imagined this feature would be like `npm link`, where a "linked" package would be symlink to local directory.
> 
> First you run `pack link` to register the dependency package directory in a local "development" package registry.
> 
> Then, run `pack link dependency` in the dependent package directory to generate a file like `.pack-dev.json`. Pack would check this file and decide to bypass other ways to fetch a package.
> 
> I remembered `yarn link` simply symlink `node_modules/package-name` instead of some special file. Maybe it's ok to do the same with Idris vendor directory? `node_modules` is often in `.gitignore`, but `vendor` is often not, and not designed for this purpose. NPM allows different versions of a same package installed, and every project has it's own package registry (`node_modules`), so it's different.

I'm afraid this doesn't make any sense to me. Actually, it might be best to open a new issue about this with a detailed feature request and deal with cached git repos in this issue only.

**Comment by locriacyber** [comment]
> My question was, is there a git command for checking whether a certain commit is there or not?

I found this on Stack Overflow.  When you need to check if a commit is already fetched locally or not.
`git branch -r --contains <commit-sha>`

There is also this, for remote repo (you can run this command not in existing git repo)
```
           $ git ls-remote http://www.kernel.org/pub/scm/git/git.git master seen rc
           5fe978a5381f1fbad26a80e682ddd2a401966740        refs/heads/master
           c781a84b5204fb294c9ccc79f8b3baceeb32c061        refs/heads/seen
```

**Comment by stefan-hoeck** [comment]
Added in #203 .
