### ISSUE TITLE
[ discussion, code style ] Arrows in vertical function signatures

### ISSUE THREAD

**Issue by buzden** [stefan-hoeck/idris2-pack#193]
Beware of bikeshedding!

When contributing to `pack`, I try to preserve existing code style. But there is one thing that makes this annoying and hard for me: it is the placement of arrows at verticalised function signatures. I.e., existing

```idris
findInAllParentDirs :  HasIO io
                    => (Body -> Bool)
                    -> Path Abs
                    -> EitherT PackErr io $ List $ File Abs
```

vs.

```idris
findInAllParentDirs : HasIO io =>
                      (Body -> Bool) ->
                      Path Abs ->
                      EitherT PackErr io $ List $ File Abs
```

For me, arrow belongs to the parameter on the left, because it really-really changes the meaning of it. For me, cognitive load of understanding the latter formatting is sufficiently less. Also, when adding a new parameter to an existing function, again, it's much less work to understand what to do and how to not to mess up what's already there.

So, the question is: @stefan-hoeck is it important to you that the current styling is used, or it is an arbitrary choice (or, maybe, a Haskeller habit) that can be revisited?

**Comment by stefan-hoeck** [comment]
I think the same style should be used throughout the code base. I have accustomed myself to using the style you see in the code, which is used in all/most of my Idris packages, so I'm afraid I'm not going to change that (unless there are very strong reasons convincing to do otherwise).

**Comment by buzden** [comment]
> I think the same style should be used throughout the code base.

If we are talking about whole `pack`, it's not a problem to have the same style throughout, see https://github.com/buzden/idris2-pack/commit/6c265bfa2c8c2ed37f53aeca249ce7fe612e2059

> so I'm afraid I'm not going to change that.

Okay, that's anyway about personal preference and experience. So, closing, then.

**Comment by stefan-hoeck** [comment]
Sorry, I probably was too negative in my last comment, especially since I just now realized what the actual difficulty is: We can't see, whether an argument is an auto-implicit without looking at the arrow on the next line. That's indeed something I haven't considered before. Let's do the following: Since everybody likes some decent bikeshedding from time to time, I'll post on the Idris discord asking the community about people's favorite style for lengthy function signatures. If we can agree on a solution, it probably makes sense to adapt to this newly established best practice.

**Comment by stefan-hoeck** [comment]
I have thought again about this after all the talk on Discord. Here's my suggestion:

```idris
module Style

import Data.IORef
import Data.SortedMap

foo :
     HasIO io
  => {auto ref : IORef (SortedMap String Nat)}
  -> String
  -> Nat
  -> io ()
```

Core ideas: 

- Long type signatures should be safe under function renaming : Start them on a new line.
- Prefix each line with an arrow, but use plain except for interfaces, which should be listed at the very beginning of the signature
- Use `{auto ...}` syntax plus single errors for auto implicits that are not interfaces

@buzden: What do you think?

**Comment by stefan-hoeck** [comment]
Thanks for the detailed answer. I was asking for your opinion in particular because you started this discussion by opening this issue. I can see your points - they are all valid, but they are also very much a matter of taste and personal preference. The opinions in the discussion on discord varied quite a bit, and I perceived no clear favorite there.

About interfaces going first: I'm aware this is not always possible, so there might be exceptions.

Personally, for me arrows coming last just don't look right and make the line harder to read than aligned arrows at the beginning of the line. At the same time - as was mentioned by other people on discord - using `{auto ...} ->` instead of the more concise `=>` makes auto-implicits stand out more.

Perhaps one day, we as a community will come up with some best practice and automatic linter. Until such times, I think I'll stick to the style mentioned above. I'll close this for now, as its an opinionated matter, and we are unlikely to come to an agreement here, which is not a bad thing.
