### ISSUE TITLE
[ regression ] Fatal error after `pack switch HEAD`

### ISSUE THREAD

**Issue by buzden** [stefan-hoeck/idris2-pack#205]
I did `pack switch HEAD` and after successful finish of this command `pack info` gives

```
fatal: couldn't find remote ref pack
[ fatal ] Error when executing system command.
          Command: "git" "fetch" "-q" "origin" "pack"
          Error code: 128
```

**Comment by buzden** [comment]
After `pack switch latest` everything starts work normally, and after that running `pack switch HEAD` again also gives this behaviour of `pack info`.

**Comment by stefan-hoeck** [comment]
I'm not sure about this. `pack switch HEAD` is not an officially supported thing to do, because instead of using concrete commits, `HEAD.db` lists the branches from which to fetch the latest commit. I guess this error comes from the `spidr` package, which lists `pack` as the branch to use.

So, in order to support this, we need to give `pack switch HEAD` some special treatment, such as changing all commits to `MetaCommit` when parsing the `HEAD.db`.

On the other hand, all of this is already supported via custom entries in `pack.toml` files, so I'm not sure it's worth the additional complexity. But perhaps you could share some details about your use case?

**Comment by buzden** [comment]
> `pack switch HEAD` is not an officially supported thing to do

Oh, really? I used it only because it was listed in the bash completion O_O That's why I thought it is something meant to be working.

> But perhaps you could share some details about your use case?

I thought that `pack switch HEAD` being listed in bash completion is the way to update the Idris compiler to the very last commit even if it's not present in any nightly collection. I was rushing to apply recent changes of the compiler.

**Comment by stefan-hoeck** [comment]
You know, that might be a valid use case: For all packages listed in `HEAD.db` use the very latest commit. If we interpret it like that (and we probably should!), then `HEAD.db` needs to be parsed as if all commits given were `[branch]:latest` instead of just `[branch]`. Best thing would of course be to change all entries to exactly that, but that would make `HEAD.db` unreadable for older versions of pack.

I'll keep this open and try to come up with a solution.

**Comment by stefan-hoeck** [comment]
I added support for using `pack switch HEAD` in #207 . You only need to run `pack switch HEAD` once to set `collection` in the global `pack.toml` file to `"HEAD"`. Pack will then fetch and use the latest commits of all packages if no cached commit is yet available. To force re-fetching the latest commits, run `pack fetch`. This is similar to using `commit = "latest:[branch]"` in a custom package description.
