### ISSUE TITLE
`pack gc` fails to clear temporary storage

### ISSUE THREAD

**Issue by AlgebraicWolf** [stefan-hoeck/idris2-pack#253]
I ran into an issue where pack had run out of `.tmpXY` directories. As far as I understand, `pack gc` is supposed to fix this. However, when trying to run `pack gc`, instead of `pack` attempting to clear out the storage, error message re-appears:

```
[ fatal ] Failed to create temporary directory.
          Please check directory `PACK_DIR` and make sure to remove
          all `.tmpXY` directories you no longer need.
```

**Comment by stefan-hoeck** [comment]
Thanks for reporting this. There is no easy way around the issue you describe, because the garbage collector requires itself a temporary directory. However, I addressed this in PR #254 in such a way that users will only experience the error described here if they keep ignoring pack's (new) warning about too many temporary directories being taken.
