### ISSUE TITLE
What `packagePath` boolean field is for?

### ISSUE THREAD

**Issue by Russoul** [stefan-hoeck/idris2-pack#256]

**Comment by stefan-hoeck** [comment]
It's for applications such as the Idris compiler and idris2-lsp which require access to the Idris package path to work correctly.

When pack installs an application, it compiles the corresponding executable and places it at the correct location in `$PACK_DIR/install/`. It then creates a wrapper script at `$PACK_DIR/bin` for finding and running the application based on the current package collection. This wrapper script can set up an environment for the application to run in if necessary. Since pack installs Idris packages at custom locations, applications such as the Idris compiler need to be told where packages are installed by means of envirionment variables.

If this flag is set to true, Idris will set those environment variables in the wrapper script. Here's the wrapper script for my idris2-lsp installation:

```sh
#!/bin/sh

APPLICATION="$(/home/hock/.pack/bin/pack app-path lsp)"
export IDRIS2_PACKAGE_PATH="$(/home/hock/.pack/bin/pack package-path)"
export IDRIS2_LIBS="$(/home/hock/.pack/bin/pack libs-path)"
export IDRIS2_DATA="$(/home/hock/.pack/bin/pack data-path)"


$APPLICATION "$@"
```

And here's the wrapper script for my installation of fix-whitespace (no need for the package path):

```sh
#!/bin/sh

APPLICATION="$(/home/hock/.pack/bin/pack app-path fix-whitespace)"


$APPLICATION "$@"
```

**Comment by Russoul** [comment]
Thanks!

**Comment by stefan-hoeck** [comment]
I'm going to close this, as the question seem to be answered. Feel free to reopen if this is not the case.

**Comment by buzden** [comment]
I was planning to adding this somewhere to the documentation before closing, but wasn't fast enough

**Comment by stefan-hoeck** [comment]
In that case I'll happily reopen it! Thanks, buzden.
